### ISSUE TITLE
Worksのアイコンを四角に統一する

### ISSUE THREAD

**Issue by tyanio** [cammelworks/CammelPages#23]
Worksのアイコンに統一性がないので実装する

- [x] 各アイコンを用意する

  - [x] AR-beats

  - [x] ByebyeVirus @kugimasa 

  - [x] Name_it @daigo0907 

- [x] 実装する

**Comment by tyanio** [comment]
## Appstore黒
[download-on-the-app-store-ja-jp.zip](https://github.com/cammelworks/CammelPages/files/5684236/download-on-the-app-store-ja-jp.zip)

## AR-beats
![AR-BeatsIcon](https://user-images.githubusercontent.com/19584781/102003868-8e5af080-3d4e-11eb-8b12-16d0e16a72b7.png)

**Comment by tyanio** [comment]
## ByeByeVirus
<img width="200" alt="スクリーンショット 2020-12-13 14 19 10" src="https://user-images.githubusercontent.com/19584781/102003921-0de8bf80-3d4f-11eb-8c4f-35048f143f62.png">

## Codetyper
![CodeTyperIcon](https://user-images.githubusercontent.com/19584781/102003957-4ee0d400-3d4f-11eb-8961-4466db72da46.png)

**Comment by daigo0907** [comment]
## name_it
![name_it_ffffff_2d3047_Sheep](https://user-images.githubusercontent.com/40502921/102004056-8b60ff80-3d50-11eb-99ff-c08bffa5aa65.png)
